### ISSUE TITLE
Error while installing on Mac OS X

### ISSUE THREAD

**Issue by rogermeijer** [chocolateboy/pmsencoder#1]
I get the following error while trying to install PMSEncoder on Mac OS X

imac:~ rogermeijer$ perl /Users/rogermeijer/Downloads/PMSEncoder/MakeFile.pl
Can't locate inc/Module/Install.pm in @INC (@INC contains: /Users/rogermeijer/Library/ActivePerl-5.10/lib /usr/local/ActivePerl-5.10/site/lib /usr/local/ActivePerl-5.10/lib .) at /Users/rogermeijer/Downloads/PMSEncoder/MakeFile.pl line 8.
BEGIN failed--compilation aborted at /Users/rogermeijer/Downloads/PMSEncoder/MakeFile.pl line 8.

My Perl version is:

imac:~ rogermeijer$ perl -v

This is perl, v5.10.1 built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2009, Larry Wall

Binary build 1007 [291969] provided by ActiveState http://www.ActiveState.com
Built Jan 27 2010 03:07:49

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Can you please tell me how to install PMSEncoder correctly? Thanks!

Kind regard,

Roger Meijer

**Comment by chocolateboy** [comment]
Make sure you're running `perl Makefile.PL` from the directory you unpacked/checked out PMSEncoder to. e.g.

`cd /Users/rogermeijer/Downloads/PMSEncoder; perl ./Makefile.PL`

**Comment by rogermeijer** [comment]
Now the installation worked (took a while with a lot of codes), but now my PS3 Media Server isn't working anymore. My Sony Bravia can't find the server anymore... What to do?

Thanks for the quick response!

Roger

**Comment by chocolateboy** [comment]
Make sure you haven't broken your PMS conf. See [Troubleshooting](http://github.com/chocolateboy/pmsencoder/blob/master/README.md#Troubleshooting) for more details.

**Comment by rogermeijer** [comment]
Yes, but I don't know how to input the 'pmsencoder --version' or '--test' command...?

And what is the correct path for me --> mencoder_path = \/home\/<username>\/perl5\/bin\/pmsencoder ?

**Comment by chocolateboy** [comment]
Sorry. I can't help you if you don't know where you installed it.

The build-from-source option is for people who are comfortable building and installing Perl modules, as stated several times on the forum. Your best bet is to remove the `mencoder_path = ...` line from PMS.conf and wait for the plugin.

**Comment by rogermeijer** [comment]
Ok, I must admit that I'm not familiar with Perl modules. But now my PS3 Media Server isn't working anymore (even after deleting the mencoder_path line). Can you please tell me what to do?

And when do you think the plugin will be available? Thanks

**Comment by chocolateboy** [comment]
> Can you please tell me what to do?

I honestly have no idea. PMSEncoder is an MEncoder wrapper. It only gets used if you explicitly use it, either from the command line or by manually configuring PMS to use it. If it's not mentioned in your PMS.conf then as far as PMS is concerned it doesn't exist..

Try moving MEncoder Web (i.e. MEncoder) back down to wherever it was on the Web Video Streaming Engines list in the PMS GUI. Or disable it.

Failing that, create a backup copy of your PMS.conf, then quit PMS, delete PMS.conf, and restart PMS and re-enter your details. If PMS can't find your TV since you edited that file, the most likely reason is that it's become corrupted in some way, or you've somehow deleted your network settings. Enter and save them again in the GUI when PMS starts as a blank slate.

If all else fails, your best bet is to post your debug.log in the [Mac OS X subforum](http://ps3mediaserver.org/forum/viewforum.php?f=7).

**Comment by rogermeijer** [comment]
Hi, sorry I have one last question. How is it possible to completely reinstall PS3 Media Server? PMS still works with old settings after deleting PMS.conf or after deleting the whole package and installing it again.

I've posted my problem on the PMS forum ( http://ps3mediaserver.org/forum/viewtopic.php?f=7&t=5740 ), so hopefully this will also lead to some answers. Maybe you can look at it?

Thanks again for helping me out here. I really think it has something to do with the installation of PMSEncoder, because before that it worked perfect.

Roger

**Comment by rogermeijer** [comment]
Dear chocolateboy,

I just want to say that PMS is working again, all the network settings changed. When do you think the installer of PMSEncoder for the Mac will be online? Thanks

Roger

**Comment by chocolateboy** [comment]
> When do you think the installer of PMSEncoder for the Mac will be online?

Almost a year later :-)

http://tinyurl.com/6fd4v69
