### ISSUE TITLE
Xbox 360 Support?

### ISSUE THREAD

**Issue by 700zx** [chocolateboy/pmsencoder#2]
Hi there.  I've been following your project for quite a while now and have been very excited about its progress.  This project is exactly what I've been waiting for to create an amazing media center.  What I would like to see though, since I do not own a PS3, would be support for xbox 360 streams.  Would this be hard to implement?

**Comment by chocolateboy** [comment]
Patches/feedback welcome, but I don't have access to an Xbox 360, so it's not something I can work on. Transcoding everything to WMV/WMA might work, and probably wouldn't be hard to implement, but, like I say, ...
