### ISSUE TITLE
feeds with http authentication doesn't work

### ISSUE THREAD

**Issue by tuomaslaa** [chocolateboy/pmsencoder#4]
It seems that pmsencoder doesn't support urls with format like http://username:password@http:www.domain.com/feed

Some finnish guy has done this http authentication support for PMS 1.2 but hasn't updated lately. Sources here:
http://shell.suomiscene.fi/~naali/ps3ms/ps3ms_changes_r412.zip

Could you please add this fix / feature?

**Comment by chocolateboy** [comment]
Feeds are handled by PMS, not PMSEncoder.
