### ISSUE TITLE
silly but how to print using DSL?

### ISSUE THREAD

**Issue by han5** [chocolateboy/pmsencoder#6]
I am looking to debug a script for parsing streams, but how do you actually print info to the logs?

action { print "TEST" }

**Comment by chocolateboy** [comment]
Inside `pattern` and `action` blocks, a Log4j [Logger](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/Logger.html) instance, `logger` (which logs to `pmsencoder.log`), is available e.g.:

``` groovy
logger.info(message)
logger.warn(message)
```

&c.

Or you can log to the PMS `debug.log` (from anywhere in a script) with:

``` groovy
Plugin.info(message)
Plugin.error(message)
```

To access the `Plugin` class, you'll need to place this at the top of the script:

``` groovy
import com.chocolatey.pmsencoder.Plugin
```
